/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GiveRouteImport } from './routes/give'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SeminarsRouteImport } from './routes/seminars'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeachingsIndexRouteImport } from './routes/teachings/index'
import { Route as TeachingsSlugRouteImport } from './routes/teachings/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SeminarsRoute = SeminarsRouteImport.update({
  id: '/seminars',
  path: '/seminars',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingsIndexRoute = TeachingsIndexRouteImport.update({
  id: '/teachings/',
  path: '/teachings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingsSlugRoute = TeachingsSlugRouteImport.update({
  id: '/teachings/$slug',
  path: '/teachings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/give': typeof GiveRoute
  '/library': typeof LibraryRoute
  '/outreach': typeof OutreachRoute
  '/privacy': typeof PrivacyRoute
  '/seminars': typeof SeminarsRoute
  '/terms': typeof TermsRoute
  '/teachings/$slug': typeof TeachingsSlugRoute
  '/teachings/': typeof TeachingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/give': typeof GiveRoute
  '/library': typeof LibraryRoute
  '/outreach': typeof OutreachRoute
  '/privacy': typeof PrivacyRoute
  '/seminars': typeof SeminarsRoute
  '/terms': typeof TermsRoute
  '/teachings/$slug': typeof TeachingsSlugRoute
  '/teachings': typeof TeachingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/give': typeof GiveRoute
  '/library': typeof LibraryRoute
  '/outreach': typeof OutreachRoute
  '/privacy': typeof PrivacyRoute
  '/seminars': typeof SeminarsRoute
  '/terms': typeof TermsRoute
  '/teachings/$slug': typeof TeachingsSlugRoute
  '/teachings/': typeof TeachingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/give'
    | '/library'
    | '/outreach'
    | '/privacy'
    | '/seminars'
    | '/terms'
    | '/teachings/$slug'
    | '/teachings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/give'
    | '/library'
    | '/outreach'
    | '/privacy'
    | '/seminars'
    | '/terms'
    | '/teachings/$slug'
    | '/teachings'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/give'
    | '/library'
    | '/outreach'
    | '/privacy'
    | '/seminars'
    | '/terms'
    | '/teachings/$slug'
    | '/teachings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  GiveRoute: typeof GiveRoute
  LibraryRoute: typeof LibraryRoute
  OutreachRoute: typeof OutreachRoute
  PrivacyRoute: typeof PrivacyRoute
  SeminarsRoute: typeof SeminarsRoute
  TermsRoute: typeof TermsRoute
  TeachingsSlugRoute: typeof TeachingsSlugRoute
  TeachingsIndexRoute: typeof TeachingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seminars': {
      id: '/seminars'
      path: '/seminars'
      fullPath: '/seminars'
      preLoaderRoute: typeof SeminarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachings/': {
      id: '/teachings/'
      path: '/teachings'
      fullPath: '/teachings/'
      preLoaderRoute: typeof TeachingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachings/$slug': {
      id: '/teachings/$slug'
      path: '/teachings/$slug'
      fullPath: '/teachings/$slug'
      preLoaderRoute: typeof TeachingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  GiveRoute: GiveRoute,
  LibraryRoute: LibraryRoute,
  OutreachRoute: OutreachRoute,
  PrivacyRoute: PrivacyRoute,
  SeminarsRoute: SeminarsRoute,
  TermsRoute: TermsRoute,
  TeachingsSlugRoute: TeachingsSlugRoute,
  TeachingsIndexRoute: TeachingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
